### ISSUE TITLE
Update README for local setup

### ISSUE THREAD

**Issue by hanzalahwaheed** [Open-Source-Chandigarh/Brewtopia#102]
@Varinder-Dhillon0 hey im having some trouble in setting up the project. I didn't know elsewhere to seek help.
`const apiUrl = process.env.REACT_APP_API_URL;` 
i dont know if this has got to do with hosting the project. but im not able to send api requests without this value. what do I add in the .env file since it wasnt given in the README.md. waiting for your reply.

_Originally posted by @hanzalahwaheed in https://github.com/Open-Source-Chandigarh/Brewtopia/issues/68#issuecomment-1893272690_

**Comment by hanzalahwaheed** [comment]
Please assign the issue to me. I'll update the README with proper explaination. Thanks!

**Comment by Varinder-Dhillon0** [comment]
ok @hanzalahwaheed
