### ISSUE TITLE
Un-equal box size and bad alignment button in sign form.

### ISSUE THREAD

**Issue by nepalivai** [Open-Source-Chandigarh/Brewtopia#104]
**Is your feature request related to a problem? Please describe.**
The button alignment and sign-up box size are uneven and make me frustrated to even look at it.
<img width="294" alt="image" src="https://github.com/Open-Source-Chandigarh/Brewtopia/assets/108126089/a7bf06b5-95b1-4b4b-9323-1485a715b33b">

**Describe the solution you'd like**
equal box size and align the button in middle.

**Describe alternatives you've considered**
No alternative it is normal standard in 2024.

**Comment by Varinder-Dhillon0** [comment]
ok make the login and signup buttons in center @nepalivai
