### ISSUE TITLE
Feature: providing users options to update cart.

### ISSUE THREAD

**Issue by maadi7** [Open-Source-Chandigarh/Brewtopia#11]
An overiew can be seen in red mark in the below image. this will enhance customer convienence.

     
     
![err3](https://github.com/Open-Source-Chandigarh/Brewtopia/assets/95737654/eba4b841-630d-46bf-a444-97f38ed90663)

**Comment by Varinder-Dhillon0** [comment]
hey @maadi7 yes you can work on this. This issue is already assigned but whoever does it first i will accept it.

**Comment by Varinder-Dhillon0** [comment]
hey @maadi7 issue has been resolved . I am closing this now.
