### ISSUE TITLE
feat: OAuth (Google) Sign-Up on Registration Page

### ISSUE THREAD

**Issue by Niharika0104** [Open-Source-Chandigarh/Brewtopia#111]
**Is your feature request related to a problem? Please describe.**
As part of enhancing our user registration process, we propose the implementation of an OAuth sign-up feature, specifically allowing users to register using their Google credentials.

**Describe the solution you'd like**
Integrate OAuth for Google sign-up to simplify the registration process and improve user experience.

**Describe alternatives you've considered**
I think the proposed resolution would be sufficient.

**Comment by deepoa** [comment]
hi @Varinder-Dhillon0  if it is not solved i can do that @Varinder-Dhillon0 ?

**Comment by Varinder-Dhillon0** [comment]
hey @deepoa you can start working on it

**Comment by Niharika0104** [comment]
@Varinder-Dhillon0  If @deepoa didnt start working on the issue.I would like to take the issue?Please let me know.

**Comment by Varinder-Dhillon0** [comment]
yes it is already assigned to you @Niharika0104

**Comment by Niharika0104** [comment]
@Varinder-Dhillon0  okay.I will start working on it.
