### ISSUE TITLE
feat:Implement "Forgot Password" Feature on Sign-In Page

### ISSUE THREAD

**Issue by Niharika0104** [Open-Source-Chandigarh/Brewtopia#112]
**Is your feature request related to a problem? Please describe.**
Currently, we lack a "Forgot Password" feature on the sign-in page. This issue aims to address this by creating a dedicated page for password recovery. When users click on the "Forgot Password" button on the sign-in page, they should be redirected to the password recovery page.

**Describe the solution you'd like**
Create a new "Forgot Password" page with the following functionality:
   - User prompted to enter their username.
   - If the username exists in the database, display password and confirm password fields.
   - If the username does not exist, show an error message indicating that the user doesn't exist.

**Describe alternatives you've considered**
When the user submits the form with a valid username, generate a secure token and send a password reset link to the user's registered email.

### **Should I follow the email based approach or non-email based approach?**

**Comment by Varinder-Dhillon0** [comment]
you should follow email based approach @Niharika0104

**Comment by Varinder-Dhillon0** [comment]
replace username with email

**Comment by Niharika0104** [comment]
But the login form has only username.So before sending email,I have to check whether given user exists or not.If the user exists then I will show email Input field,else I will throw a validation error saying that user doesnt exists.Does that work for you?

**Comment by Niharika0104** [comment]
@Varinder-Dhillon0 Is it fine if I use nodemailer and google app password for sending mails.Also,I'm using jwt tokens  for carrying sensitive data.I'm also making sure link is valid only for one time.

**Comment by patelhitarth08** [comment]
I've successfully added a new feature. Users can now utilize a "Forgot Password" link to access a page where they input their email address. Upon submission, an email containing a password reset link will be sent to the user, allowing them to reset their password by following the link. Please assign this issue to me.

**Comment by Varinder-Dhillon0** [comment]
@patelhitarth08 this issue is already assigned
