### ISSUE TITLE
Redesigning of Filter Section

### ISSUE THREAD

**Issue by Manishak798** [Open-Source-Chandigarh/Brewtopia#116]
**Is your feature request related to a problem? Please describe.**
Redesigning of Filter Section will make the website look more appealing and will also enhance the user experience. I am a SWOC'24 Mentor raising this issue for contributors.

**Describe the solution you'd like**
Updating the stylesheet of every filter component will help to improve user experience.

**Additional context**
![image](https://github.com/Open-Source-Chandigarh/Brewtopia/assets/90680330/f5557053-1f20-4ed3-aa49-eef7d3e36582)

**Comment by Varinder-Dhillon0** [comment]
sure @Manishak798 send me for review here before pr

**Comment by Varinder-Dhillon0** [comment]
ohh ok @Manishak798

**Comment by EAGLEARCHER** [comment]
@Varinder-Dhillon0 can you please assign me this under SWOC'24

**Comment by Varinder-Dhillon0** [comment]
sure @EAGLEARCHER

**Comment by EAGLEARCHER** [comment]
hey @Varinder-Dhillon0 I have completed the design of the filter section. Please check this and let me know about further improvements and fixes
![Screenshot 2024-02-09 221801](https://github.com/Open-Source-Chandigarh/Brewtopia/assets/92213232/be3421f1-020a-4389-a7ca-c52303df9433)
![Screenshot 2024-02-09 221832](https://github.com/Open-Source-Chandigarh/Brewtopia/assets/92213232/065699bf-f194-4232-bace-ad6dcaed4d4b)

**Comment by EAGLEARCHER** [comment]
the new filter sidebar
![image](https://github.com/Open-Source-Chandigarh/Brewtopia/assets/92213232/bb70790c-5f67-4b8b-9367-6cced42d4638)

![image](https://github.com/Open-Source-Chandigarh/Brewtopia/assets/92213232/e2e04bdd-f2f4-44bd-8523-2d87775cd5f9)

**Comment by Varinder-Dhillon0** [comment]
add padding to left @EAGLEARCHER

**Comment by EAGLEARCHER** [comment]
please check this out and if there are any changes please specify one for further improvements. 
![image](https://github.com/Open-Source-Chandigarh/Brewtopia/assets/92213232/08287d91-c412-4419-92a2-b18cd09702f4)
