### ISSUE TITLE
Changing product card UI and adding hover effects

### ISSUE THREAD

**Issue by nandita27iitp** [Open-Source-Chandigarh/Brewtopia#12]
- Changing card design
- Adding hover effects to cards
- Adding details section to each product

@Varinder-Dhillon0 Please assign this issue to me.

**Comment by Varinder-Dhillon0** [comment]
@nandita27iitp can you tell me what changes you will do to card design

**Comment by nandita27iitp** [comment]
> @nandita27iitp can you tell me what changes you will do to card design

![Screenshot_2024_0101_171828.jpg](https://github.com/Open-Source-Chandigarh/Brewtopia/assets/94813932/72fbb53c-ee73-485d-bcaa-9aa360fd213c)

Something like this

Also add hover effects on the card and a details section of that menu item

**Comment by Varinder-Dhillon0** [comment]
yes go ahead @nandita27iitp and please send me pic. here for review before pr.

**Comment by Varinder-Dhillon0** [comment]
hey @nandita27iitp this is a nice design but description for every product will be too long and not necessary can you think something else for this space.

**Comment by Varinder-Dhillon0** [comment]
okay @nandita27iitp  and try to make height and width small . And this product list part was made responsive so make product cards so they don't break the layout.

**Comment by nandita27iitp** [comment]
![image](https://github.com/Open-Source-Chandigarh/Brewtopia/assets/94813932/8ad11573-f42c-493e-b114-26e6edaec1b1)


@Varinder-Dhillon0 Pls review it.

**Comment by Varinder-Dhillon0** [comment]
This is lookng great @nandita27iitp

**Comment by nandita27iitp** [comment]
> This is looking great @nandita27iitp 

Should I PR then?

**Comment by Varinder-Dhillon0** [comment]
sure @nandita27iitp
