### ISSUE TITLE
[BUG] :  Passwords of length 6-7 characters are not accepted

### ISSUE THREAD

**Issue by bj-jiwrajka** [Open-Source-Chandigarh/Brewtopia#13]
When we try to sign up and create a new password. The password length is required to be atleast 8 characters. However, the popup says it must be of 6 characters or more. So, it should accept passwords of length 6 and 7, I would like to fix that

Screenshot:
![image](https://github.com/Open-Source-Chandigarh/Brewtopia/assets/97835955/c67ab94f-ec01-4c0e-bd26-2377674b4ae6)

**Comment by Varinder-Dhillon0** [comment]
@bj-jiwrajka go ahead and fix it!
