### ISSUE TITLE
Storing passwords using encryption

### ISSUE THREAD

**Issue by Varinder-Dhillon0** [Open-Source-Chandigarh/Brewtopia#14]
Right now passwords on database are stored in plain text format!

**_what you need to do_**
- Use bcrypt to hash passwords 
- Store in encrypted format
- decrypt at login endpoint

**Comment by dishamodi0910** [comment]
I would like to work on this issue!
Please assign it to me under SWOC24!

**Comment by Varinder-Dhillon0** [comment]
yes @dishamodi0910 go ahead !
