### ISSUE TITLE
[BUG] : Enable Login and Signup Submission on "Enter" Key Press

### ISSUE THREAD

**Issue by bj-jiwrajka** [Open-Source-Chandigarh/Brewtopia#16]
Currently, after entering the username and password, users are required to click on the signup/in button to complete the process. To enhance user convenience and streamline the experience, I propose activating the signup/in functionality when users press the "Enter" key after inputting their credentials.

**Comment by bj-jiwrajka** [comment]
@Varinder-Dhillon0 please assign it to me

**Comment by Varinder-Dhillon0** [comment]
Are you still working on this one @bj-jiwrajka ?

**Comment by bj-jiwrajka** [comment]
> Are you still working on this one @bj-jiwrajka ?

actually yes, I'll make the PR as soon as I get back to campus, due to travelling I was unable to do , sorry for the delay:)

**Comment by Varinder-Dhillon0** [comment]
hey make a pr @bj-jiwrajka

**Comment by bj-jiwrajka** [comment]
> hey make a pr @bj-jiwrajka

I've made the PR, please review
