### ISSUE TITLE
Improve footer designing

### ISSUE THREAD

**Issue by dishamodi0910** [Open-Source-Chandigarh/Brewtopia#19]
The current footer is also looking awesome. I would like to make it more catchy by adding some animation aligning with theme.

**Comment by dishamodi0910** [comment]
@Varinder-Dhillon0 Please assign me this issue under SWOC24

**Comment by bj-jiwrajka** [comment]
@Varinder-Dhillon0 I would like to improve the UI of footer, can you assign it to me?

**Comment by Varinder-Dhillon0** [comment]
Yes @bj-jiwrajka
