### ISSUE TITLE
fix backend code 

### ISSUE THREAD

**Issue by itsmeabhishek03** [Open-Source-Chandigarh/Brewtopia#2]
hello i can modify your backend code by modifing following code - 

1) Use Async/Await in Database Connection
2) Improve error handling by providing more informative messages and logging
3) Provide default values for environment variables or ensure they exist before using them to prevent unexpected issues.

please assign this issue to me under SWOC.

**Comment by younikarn** [comment]
Can I take this issue? Please assign it to me under SWOC'24

**Comment by itsmeabhishek03** [comment]
> Can I take this issue? Please assign it to me under SWOC'24

hey @younikarn i am not project admin.
I am a participant like you that's why i raise this issue so that i can work on it. Thank You

**Comment by SadanandMiskin** [comment]
Please can You assign the issue , I can solve this.

**Comment by Varinder-Dhillon0** [comment]
@itsmeabhishek03 Great observations ! you can go ahead and start working on it.

**Comment by Anand930singh** [comment]
Can I work on this issue? @itsmeabhishek03

**Comment by Varinder-Dhillon0** [comment]
Are you still working on this one @itsmeabhishek03

**Comment by itsmeabhishek03** [comment]
> Are you still working on this one @itsmeabhishek03

Yes I am working on it please give me sometime I will raise PR today late night
