### ISSUE TITLE
Solving bug of extra white space at bottom and aligning the page with the theme of website!

### ISSUE THREAD

**Issue by dishamodi0910** [Open-Source-Chandigarh/Brewtopia#20]
![image](https://github.com/Open-Source-Chandigarh/Brewtopia/assets/106090499/75223bab-ecc5-478f-8147-ce59857efede)

**Comment by Varinder-Dhillon0** [comment]
yes go ahead @dishamodi0910 !

**Comment by Varinder-Dhillon0** [comment]
this is issue was fixed @dishamodi0910
