### ISSUE TITLE
'Go to top' Button 

### ISSUE THREAD

**Issue by AaadityaG** [Open-Source-Chandigarh/Brewtopia#22]
'Go to top' Button after scrolling...

Please allow me to work on it for SWOC24

**Comment by Varinder-Dhillon0** [comment]
Ok @AaadityaG go ahead!

**Comment by bj-jiwrajka** [comment]
@Varinder-Dhillon0 can I work on it?

**Comment by Varinder-Dhillon0** [comment]
Go ahead @bj-jiwrajka

**Comment by AaadityaG** [comment]
> Go ahead @bj-jiwrajka 

Sir I am working on it please let me do it!
