### ISSUE TITLE
route login error

### ISSUE THREAD

**Issue by Aastha1316** [Open-Source-Chandigarh/Brewtopia#25]
after login "/login" path return app.js , this will redirect to "/"

issue  
![image](https://github.com/Open-Source-Chandigarh/Brewtopia/assets/115647023/a13a33f3-a41b-47ca-8394-2c93d7bfbb59)

**Comment by Aastha1316** [comment]
please assign me @Varinder-Dhillon0

**Comment by Varinder-Dhillon0** [comment]
ok go on with this one @Aastha1316
