### ISSUE TITLE
Follow us Icons

### ISSUE THREAD

**Issue by Avadhut20** [Open-Source-Chandigarh/Brewtopia#28]
Social icons in the footer section are not working. It is not redirecting to social platforms.
![Screenshot (35)](https://github.com/Open-Source-Chandigarh/Brewtopia/assets/111897568/d1bf4b32-c257-421f-9b40-44237961cc2c)

Expected behavior:
It should redirect to social platforms.

Can you please assign this issue to me under SWOC?

**Comment by Varinder-Dhillon0** [comment]
yes @Avadhut20 
github - https://github.com/Varinder-Dhillon0
linkedin - https://www.linkedin.com/in/varinder-dhillon-5b8420263/
twitter - https://twitter.com/varinder_d0
