### ISSUE TITLE
Admin Page UI

### ISSUE THREAD

**Issue by Varinder-Dhillon0** [Open-Source-Chandigarh/Brewtopia#29]
Make an admin page dashboard frontend part.
Use this for an example https://davur.dexignzone.com/react/demo/dashboard.

**_what you need to do:-_**
- make only frontend part
- use example values
- skip charts part
- make navbar and navigating side bar.

**Comment by Muskan626bidani** [comment]
can you assign this issue to me

**Comment by Varinder-Dhillon0** [comment]
go ahead @Muskan626bidani

**Comment by Muskan626bidani** [comment]
https://github.com/Open-Source-Chandigarh/Brewtopia/pull/59
this is linked pr for this issue
