### ISSUE TITLE
responsive for every device.

### ISSUE THREAD

**Issue by maadi7** [Open-Source-Chandigarh/Brewtopia#3]
Making the whole app resposive for all devices.

**Comment by Dhananjayshukla1** [comment]
I want to contribute please assign me.

**Comment by younikarn** [comment]
Can I take this issue? Please assign it to me under SWOC'24

**Comment by subhasou26** [comment]
can I take the issue? I am under SWOC'2024. I can make the app responsive.
![Uploading image.png…]()

**Comment by Varinder-Dhillon0** [comment]
@maadi7 yes you can make the product list part responsive! I am making this responsive in parts to solve so work can be done fast!
