### ISSUE TITLE
Storing cart items quantities to backend

### ISSUE THREAD

**Issue by Varinder-Dhillon0** [Open-Source-Chandigarh/Brewtopia#30]
Try to solve this issue.
For any issues contact me here.

**Comment by apala7778** [comment]
hi, I'm a mern stack developer. I would like to fix to this issue. can you elaborate more on this? we are trying to reflect total items in the cart for a particular user?

**Comment by Varinder-Dhillon0** [comment]
Cart is stored and updated in app.js. The cart items quantity is not listed there for storing you need to fix that.

**Comment by sohail300** [comment]
@Varinder-Dhillon0 Can u please assign this issue to me? I would like to work on it.

**Comment by Varinder-Dhillon0** [comment]
yes @sohail300

**Comment by sohail300** [comment]
Sure, will keep u updating on this as I build it.

**Comment by Varinder-Dhillon0** [comment]
hey @sohail300 are you still working on this issue??

**Comment by sohail300** [comment]
Yes, I want 2 more days.

**Comment by Varinder-Dhillon0** [comment]
go ahead @ayann07
