### ISSUE TITLE
It should login by pressing the enter button on key bord

### ISSUE THREAD

**Issue by subhasou26** [Open-Source-Chandigarh/Brewtopia#32]
![image](https://github.com/Open-Source-Chandigarh/Brewtopia/assets/83156210/d9c4317f-2710-45f5-bb85-1e295d400b3c)
when we try to log in or signup by entering all data and pressing the enter button it doesn't work. It is easy to press the enter button than press the button by mouse .
Could you please sign me this issue under SWOC'2024?

**Comment by Varinder-Dhillon0** [comment]
hey @subhasou26 this issue has already been raised and assigned if this is not solved till tommorow i will assign it to you.

**Comment by subhasou26** [comment]
ok
