### ISSUE TITLE
Total price in the cart is undefined

### ISSUE THREAD

**Issue by apala7778** [Open-Source-Chandigarh/Brewtopia#35]
![Screenshot 2024-01-02 202709](https://github.com/Open-Source-Chandigarh/Brewtopia/assets/109547528/16aae3a8-b6a4-4a07-8996-7a77cbcc3f7f) 

The total price of items selected is undefined in the cart.

**Comment by vrun1208** [comment]
@Varinder-Dhillon0 Hi, can you assign me to this issue?

**Comment by Varinder-Dhillon0** [comment]
you can fix this one @apala7778

**Comment by Govind516** [comment]
Is the issue still open ? If so, then Please assign it to me under SWOC S4.

**Comment by Varinder-Dhillon0** [comment]
go ahead @Govind516

**Comment by Govind516** [comment]
Resolved and Sent you the PR #66
