### ISSUE TITLE
unassigned path will redirect to homepage/404; payment route should be protected

### ISSUE THREAD

**Issue by Aastha1316** [Open-Source-Chandigarh/Brewtopia#38]
unassigned path
![image](https://github.com/Open-Source-Chandigarh/Brewtopia/assets/115647023/303d924c-8ce3-4521-9c0b-08034ab761c2)

unprotected payment route 
![image](https://github.com/Open-Source-Chandigarh/Brewtopia/assets/115647023/6fd3d7af-b370-451a-876f-285dd2a61869)

**Comment by Aastha1316** [comment]
please assign @Varinder-Dhillon0

**Comment by Varinder-Dhillon0** [comment]
you can do the unassigned path one @Aastha1316
