### ISSUE TITLE
Make footer responsive

### ISSUE THREAD

**Issue by Varinder-Dhillon0** [Open-Source-Chandigarh/Brewtopia#43]

**Comment by Anand930singh** [comment]
Can I work on this @Varinder-Dhillon0

**Comment by Varinder-Dhillon0** [comment]
yes @Anand930singh

**Comment by Varinder-Dhillon0** [comment]
Footer is responsive now @Anand930singh you should remove overflow-x on small screens and get me a pr

**Comment by Anand930singh** [comment]
> Footer is responsive now @Anand930singh you should remove overflow-x on small screens and get me a pr

Sure I will do that and then I will raise PR @Varinder-Dhillon0

**Comment by Anand930singh** [comment]
Done please check , If any changes required please let me know @Varinder-Dhillon0
