### ISSUE TITLE
Search Bar

### ISSUE THREAD

**Issue by venkataraviraja5** [Open-Source-Chandigarh/Brewtopia#46]
if we implement search functionality user can search their items..........if you like this functionality please assign to me

**Comment by Varinder-Dhillon0** [comment]
That will be great @venkataraviraja5

**Comment by venkataraviraja5** [comment]
@Varinder-Dhillon0 okay

**Comment by venkataraviraja5** [comment]
![Screenshot 2024-01-04 171335](https://github.com/Open-Source-Chandigarh/Brewtopia/assets/131418248/242b31ee-3fd6-4546-a8e4-4a29452f707b)

iplemented search bar please review this @Varinder-Dhillon0

**Comment by Varinder-Dhillon0** [comment]
style it and send a video of its working here @venkataraviraja5

**Comment by venkataraviraja5** [comment]
https://drive.google.com/file/d/1OxRRAJ6SI0e1QEwz9lBg27jEnAiNlut0/view?usp=drive_link

here is the video link please go through that @Varinder-Dhillon0

**Comment by Varinder-Dhillon0** [comment]
That is great work @venkataraviraja5 
make a pr
