### ISSUE TITLE
[BUG]: Unable to Reduce Quantities for Multiple Items in Shopping Cart

### ISSUE THREAD

**Issue by bj-jiwrajka** [Open-Source-Chandigarh/Brewtopia#5]
### Bug Description

When users select multiple quantities of a single item in the shopping cart and later attempt to reduce the quantity for one or more of those items, there is no option available to do so. The system does not provide a way to decrease the quantity of individual items once they have been added to the cart in multiples

### Expected Behavior:
Users should be able to easily decrease the quantity of individual items in the shopping cart when multiple quantities have been selected.

### Actual Behavior:
There is no option available to reduce the quantity of individual items in the shopping cart once multiple quantities have been selected.

**Comment by SadanandMiskin** [comment]
Please assign me the issue , I can solve it

**Comment by Muhammad-Owais-Warsi** [comment]
Hey, can i work on this issue...

**Comment by Varinder-Dhillon0** [comment]
@bj-jiwrajka Nice observations !
 _**what i want you to do**_
- shift range bar from products to cart window 
- allowing users to change product quantity from there
- while also ensuring everything works just like before
