### ISSUE TITLE
Contributors Section in Readme

### ISSUE THREAD

**Issue by Varinder-Dhillon0** [Open-Source-Chandigarh/Brewtopia#54]
Add a contributors section to readme where profile pictures and names of contributors will be displayed .
Make it right after the installation process.

**Comment by nandita27iitp** [comment]
Please assign this issue to me

**Comment by Varinder-Dhillon0** [comment]
yes @nandita27iitp

**Comment by nandita27iitp** [comment]
![image](https://github.com/Open-Source-Chandigarh/Brewtopia/assets/94813932/998c27e3-26e1-4944-a1b6-f45551af2af1)
@Varinder-Dhillon0 Please review it

**Comment by Varinder-Dhillon0** [comment]
nice make a pr @nandita27iitp
