### ISSUE TITLE
UPDATING Readme: Adding Screenshots

### ISSUE THREAD

**Issue by nandita27iitp** [Open-Source-Chandigarh/Brewtopia#56]
@Varinder-Dhillon0  Please assign this issue to me

**Comment by Varinder-Dhillon0** [comment]
ok you can work on that @nandita27iitp but get me to review here before pr

**Comment by nandita27iitp** [comment]
![Uploading image.png…]()

@Varinder-Dhillon0 Pls review it

**Comment by Varinder-Dhillon0** [comment]
image is broken @nandita27iitp

**Comment by nandita27iitp** [comment]
![image](https://github.com/Open-Source-Chandigarh/Brewtopia/assets/94813932/965a30a2-1b5b-47cd-9b67-261ef4cb4392)
 
 @Varinder-Dhillon0

**Comment by Varinder-Dhillon0** [comment]
ok get me a pr
