### ISSUE TITLE
Sort By Price 

### ISSUE THREAD

**Issue by venkataraviraja5** [Open-Source-Chandigarh/Brewtopia#58]
Use can sort their items by price

**Comment by Varinder-Dhillon0** [comment]
yes you can work on that @venkataraviraja5

**Comment by venkataraviraja5** [comment]
okay @Varinder-Dhillon0

**Comment by venkataraviraja5** [comment]
can i add sort function to all items in a page or different for each section

**Comment by venkataraviraja5** [comment]
can i add sort function to all items in a page or different for each section @Varinder-Dhillon0

**Comment by Varinder-Dhillon0** [comment]
Add for all page to the right of search bar

**Comment by venkataraviraja5** [comment]
okay @Varinder-Dhillon0

**Comment by venkataraviraja5** [comment]
![Screenshot 2024-01-06 091101](https://github.com/Open-Source-Chandigarh/Brewtopia/assets/131418248/bdf091d5-ffb9-4bdc-802b-86dc8a083324)

implemented sorting function please review this @Varinder-Dhillon0

**Comment by venkataraviraja5** [comment]
hey can you please review this @Varinder-Dhillon0

**Comment by Varinder-Dhillon0** [comment]
ok make a pr @venkataraviraja5
