### ISSUE TITLE
Fix Images

### ISSUE THREAD

**Issue by Varinder-Dhillon0** [Open-Source-Chandigarh/Brewtopia#6]
There are some broken product images. 

**_What you need to do_** 
- Find images that perfectly blend with background .
- Change them in [https://github.com/Open-Source-Chandigarh/Brewtopia/blob/main/client/src/menu.js](url)

**Comment by venkataraviraja5** [comment]
i would like to work on this issue can you please assign to me

**Comment by Varinder-Dhillon0** [comment]
yes go ahead @venkataraviraja5 try to find images with white background or with tansparent background.

**Comment by venkataraviraja5** [comment]
okay

**Comment by venkataraviraja5** [comment]
![Screenshot 2024-01-02 145509](https://github.com/Open-Source-Chandigarh/Brewtopia/assets/131418248/d5b15a29-eef4-4145-9311-63126d8897c1)

after git push it is showing like this am not able to create pull request....can you help

**Comment by Varinder-Dhillon0** [comment]
you have pushed to your fork now you can create pr on github.

**Comment by venkataraviraja5** [comment]
![Screenshot 2024-01-02 202636](https://github.com/Open-Source-Chandigarh/Brewtopia/assets/131418248/55819162-6e24-40cc-a4a1-2c0986c1ab85)


i have multiple commits in my branch i want to create pull request for only one commit is it possible

**Comment by Varinder-Dhillon0** [comment]
Hey make a pr with just menu.js file

**Comment by venkataraviraja5** [comment]
PR raised this is my 1st contribution

**Comment by venkataraviraja5** [comment]
PR raised this is my 1st contribution @Varinder-Dhillon0
