### ISSUE TITLE
Admin page improvements

### ISSUE THREAD

**Issue by Varinder-Dhillon0** [Open-Source-Chandigarh/Brewtopia#61]
**_Improve admin page ui by :-_**
- making colors correct
- making sizes and fonts correct with theme
- add some animations to opening sidebar 
- Add charts 

**Links (_very important_) :-**
1.  Use this https://davur.dexignzone.com/react/demo/dashboard for improving designs and adding more sections to dashboard.
2. Use https://recharts.org/en-US/examples for the charts.

**Comment by venkataraviraja5** [comment]
i would like to work on this issue can you assign me @Varinder-Dhillon0

**Comment by Varinder-Dhillon0** [comment]
Go ahead @venkataraviraja5

**Comment by venkataraviraja5** [comment]
hey can you please unassign me i am not familar with charts...sorry for request

**Comment by Varinder-Dhillon0** [comment]
ok @venkataraviraja5

**Comment by Bikram-ghuku** [comment]
Can I work on this issue??

**Comment by Bikram-ghuku** [comment]
Can I work on this issue??

**Comment by Varinder-Dhillon0** [comment]
Sure @Bikram-ghuku

**Comment by Bikram-ghuku** [comment]
Sorry I wont be able to work on this issue, I have unassigned myself
