### ISSUE TITLE
Request for Dark Mode Implementation

### ISSUE THREAD

**Issue by rasel9t6** [Open-Source-Chandigarh/Brewtopia#65]
I believe that the implementation of a Dark Mode feature would greatly enhance the overall user experience. Dark Mode has become a popular and essential feature in modern applications, providing users with a more comfortable and visually appealing interface, especially during low-light conditions.

**Implementation Considerations:**

Toggle Switch: Include a user-friendly toggle switch in the application settings to allow users to easily switch between Light Mode and Dark Mode.
    Consistent Design: Ensure a consistent and visually pleasing design in both Light and Dark Modes to maintain a seamless user experience.
    Accessibility: Pay attention to contrast ratios and accessibility guidelines to ensure that the Dark Mode implementation is accessible to a broad range of users.

**How to Implement:**
 CSS Styles: Implement CSS styles for Dark Mode, considering color schemes, contrasts, and overall aesthetics.
    User Settings: Integrate a setting in the user preferences or application settings to enable or disable Dark Mode.

**Comment by Varinder-Dhillon0** [comment]
Hey @rasel9t6 nice idea but i don't want dark mode in this website
