### ISSUE TITLE
[BUG]: Search not working on Enter

### ISSUE THREAD

**Issue by bj-jiwrajka** [Open-Source-Chandigarh/Brewtopia#71]
**Describe the bug**
When we hit the enter key after typing something in the search box, it doesn't respond

**Expected behavior**
On clicking the enter key, it should trigger the search button

**Comment by bj-jiwrajka** [comment]
@Varinder-Dhillon0 I would like to fix this

**Comment by Varinder-Dhillon0** [comment]
ok @bj-jiwrajka pull changes from here before you make any changes
