### ISSUE TITLE
Make Navbar responsive

### ISSUE THREAD

**Issue by Varinder-Dhillon0** [Open-Source-Chandigarh/Brewtopia#72]
_**what you need to do**_

- add a hamburgger menu where navigating links can be opened
- cart and orders buttons should stay same on all screens
- ensure design will be maintained for all the screens

**Comment by iSubhamMani** [comment]
Hey @Varinder-Dhillon0 I want to work on this issue. Please assign it to me

**Comment by Varinder-Dhillon0** [comment]
ok @iSubhamMani
