### ISSUE TITLE
Adding linear motion to shapes on login pages.

### ISSUE THREAD

**Issue by Ayusht777** [Open-Source-Chandigarh/Brewtopia#73]
Incorporating motion will enhance the visual appeal when users first visit the site.

**Comment by Varinder-Dhillon0** [comment]
ok @Ayusht777 send here for review before pr

**Comment by Ayusht777** [comment]
Preview 

https://github.com/Open-Source-Chandigarh/Brewtopia/assets/106388215/f9257950-10e7-4a55-b863-e22696dad86c

**Comment by Varinder-Dhillon0** [comment]
ok get me a pr
