### ISSUE TITLE
add toggle button in password input for hiding and showing passwods in login and signup page

### ISSUE THREAD

**Issue by Aastha1316** [Open-Source-Chandigarh/Brewtopia#79]
**Is your feature request related to a problem? Please describe.**
yes it is , user should get an option to view their passwords while input in login or signup page.

**Describe the solution you'd like**
toggle button in password input to view passwords in login and signup page.

**Describe alternatives you've considered**

**Additional context**

**Comment by Aastha1316** [comment]
please assign me this issue @Varinder-Dhillon0

**Comment by Varinder-Dhillon0** [comment]
go ahead with this one @Aastha1316
