### ISSUE TITLE
Fixing Login page and Signup page layout

### ISSUE THREAD

**Issue by Varinder-Dhillon0** [Open-Source-Chandigarh/Brewtopia#8]
There is an overflow issue for login page and signup page for mobile devices.

**Comment by Anand930singh** [comment]
Can I work on this issue? @Varinder-Dhillon0

**Comment by Varinder-Dhillon0** [comment]
yes go ahead @Anand930singh

**Comment by Anand930singh** [comment]
For creating new PR do I have to create new branch @Varinder-Dhillon0

**Comment by Anand930singh** [comment]
created a pr please check @Varinder-Dhillon0
