### ISSUE TITLE
Add tags to readme

### ISSUE THREAD

**Issue by Varinder-Dhillon0** [Open-Source-Chandigarh/Brewtopia#83]
**_what you need to do_**
- Add stars tag which will show no. of stars repo got.
- forks tag
- issues tag
- other tags 

Add them right after Brewtopia headline in Readme.

**Comment by venkataraviraja5** [comment]
can you please assign this issue to me

**Comment by Varinder-Dhillon0** [comment]
yes @venkataraviraja5

**Comment by venkataraviraja5** [comment]
@Varinder-Dhillon0  small doubt...how can i see my changes in readme file....is it possible to run this file in my system can you help me

**Comment by Varinder-Dhillon0** [comment]
you can push to your own fork of this repo and see it there @venkataraviraja5

**Comment by venkataraviraja5** [comment]
@Varinder-Dhillon0 ok thanks

**Comment by Gaurav-Kushwaha-1225** [comment]
### I have resolved this Issue and created a pull request. Below is the pull request link.
[Pull Request for Issue #83](https://github.com/Open-Source-Chandigarh/Brewtopia/pull/103)
