### ISSUE TITLE
Rate limit

### ISSUE THREAD

**Issue by Varinder-Dhillon0** [Open-Source-Chandigarh/Brewtopia#84]
Currently routes on backend accessing database are not rate limited.

**_what you need to do_**
Add rate limiting to all the database accessing so that user cannot make multiple requests at once on these expensive operations.

If you have enough knowledge about this issue then ask me to assign you.

**Comment by jayant-vashisth** [comment]
Hey @Varinder-Dhillon0 , Can I take on this issue? Also, what's the max API calls limit and time window?

**Comment by Varinder-Dhillon0** [comment]
yes @jayant-vashisth 
calls limit - 10 per minute
time window - 60 * 1000

**Comment by jayant-vashisth** [comment]
@Varinder-Dhillon0, shouldn't we consider a higher limit for cart APIs? It's common for users to add or remove more than 10 items in a day, right?

**Comment by Varinder-Dhillon0** [comment]
yeah @jayant-vashisth 15 will be enough
