### ISSUE TITLE
Add sufficient sanitization to user inputs

### ISSUE THREAD

**Issue by Varinder-Dhillon0** [Open-Source-Chandigarh/Brewtopia#86]
**_Problem_**

> Currently all user inputs i.e. username and password are treated same as user provided for backend . This way user can use sql injection or other methods to send malicious data on server and run queries.

_**what you need to do**_

> Add sufficient sanitization i.e. filter the user data to protect the database.

**Comment by jayant-vashisth** [comment]
Hey @Varinder-Dhillon0 can i work on this?

**Comment by Varinder-Dhillon0** [comment]
yes @jayant-vashisth

**Comment by Paarisha1** [comment]
Can I work on it

**Comment by Varinder-Dhillon0** [comment]
yes @Paarisha1
