### ISSUE TITLE
The navbar options should be in good animation and the cart and order icon has no animaion

### ISSUE THREAD

**Issue by subhasou26** [Open-Source-Chandigarh/Brewtopia#9]
I can fix the animation part of the page, especially the nav bar options. I am from SWOC 2024 please asign the issue to me
![image](https://github.com/Open-Source-Chandigarh/Brewtopia/assets/83156210/9621ca78-b4b1-400e-89a8-8e6f718164a7)

**Comment by Varinder-Dhillon0** [comment]
yes go ahead @subhasou26

**Comment by subhasou26** [comment]
can you give me a process for how to run the project on the local machine?

**Comment by Varinder-Dhillon0** [comment]
On terminal - 
**change to client dir**
`cd client`
**run server**
`npm run start`

**Comment by subhasou26** [comment]
@Varinder-Dhillon0 After starting it shows only the login and signup screen but they are not working because the server is off, but without signup and sign how do I go to the main page for contribute?

**Comment by Varinder-Dhillon0** [comment]
hey @subhasou26 i have updated server/index.js. it should be working now.
Let me know for more issues.
