### ISSUE TITLE
trim the search value

### ISSUE THREAD

**Issue by Aastha1316** [Open-Source-Chandigarh/Brewtopia#91]
**Describe the bug**
to trim the search value to avoid searching issues

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Aastha1316** [comment]
pls assign me this issue @Varinder-Dhillon0

**Comment by Varinder-Dhillon0** [comment]
ok @Aastha1316
