### ISSUE TITLE
Improve ui for eye on signup and login

### ISSUE THREAD

**Issue by Varinder-Dhillon0** [Open-Source-Chandigarh/Brewtopia#94]
Right now ui on eye is not good 
I need you to shift it inside password and only eye visible not its background

![image](https://github.com/Open-Source-Chandigarh/Brewtopia/assets/98728916/b130dad7-a0d9-486c-8b2f-5165dfca07ab)

**Comment by Aastha1316** [comment]
#95 added login.css file which was missing in previous pr for toggle password
