### ISSUE TITLE
Improve Cart UI

### ISSUE THREAD

**Issue by sherabhai** [Open-Source-Chandigarh/Brewtopia#97]
Hey @Open-Source-Chandigarh

Checked out your website, it was demn sick, keep up the good work man!

I would like to update the Cart Section UI, as it seems pretty rough as compared to other UI elements of the Website!

![image](https://github.com/Open-Source-Chandigarh/Brewtopia/assets/78367273/6d28f238-c074-4c96-acec-945063d34b0a)

Thnks for listening to my issue, If you found it useful in any way do lemme know and we can work out on it!

Best Regards,
**Shera Bhai**

**Comment by Varinder-Dhillon0** [comment]
Thank you ! and for sure @sherabhai send me ss here before pr.

**Comment by sherabhai** [comment]
@Varinder-Dhillon0 

Just Check it Out!
If you like it and approve, will submit the PR!

![image](https://github.com/Open-Source-Chandigarh/Brewtopia/assets/156661163/3765d098-3824-48b4-8495-e9753d57fb4c)

Best Regards,
**Shera Bhai**

**Comment by Varinder-Dhillon0** [comment]
@sherabhai colors are off and not per theme change that and make layout more good.

**Comment by Varinder-Dhillon0** [comment]
hey @sherabhai change colors back to what they were however keep the changes you made to layout spacing.

**Comment by Varinder-Dhillon0** [comment]
@sherabhai  check my previous comment

**Comment by shera-bhai** [comment]
@Varinder-Dhillon0 

Is it perfect now?

![image](https://github.com/Open-Source-Chandigarh/Brewtopia/assets/78367273/44afec8e-6891-4409-ab88-b8d4cccacbd2)

**Comment by Varinder-Dhillon0** [comment]
yes @shera-bhai

**Comment by IrfanshaikH-7** [comment]
Can i suggest some UI changes on this

**Comment by shera-bhai** [comment]
@IrfanshaikH-7 
Yeah sure, much appreciated bro!

It'll be good if I could get a reference too 😅

Just lemme know and will submit the PR soon!

**Comment by IrfanshaikH-7** [comment]
**How about something like this for the layout - product and its quantity one side and the amount and quantity-counter other side?**

![Screenshot 2024-01-19 100238](https://github.com/Open-Source-Chandigarh/Brewtopia/assets/124655192/052b81f3-a6f7-4fb4-9b82-ac60551ed263)

**Comment by shera-bhai** [comment]
@Varinder-Dhillon0 

Sorry for all the delay, was busy in a Hackathon!

Actually I'm not authenticating it, normally running the App.. that's why the Username is not shown!

**Comment by Varinder-Dhillon0** [comment]
yes @shera-bhai  the one mentioned by @IrfanshaikH-7 looks great and make checkout button's text white

**Comment by shera-bhai** [comment]
@Varinder-Dhillon0 

Hope you like it!

![image](https://github.com/Open-Source-Chandigarh/Brewtopia/assets/78367273/9b96c5a3-84e8-4fc8-af6e-0ba37a52ed95)

Best Regards,
**Shera Bhai**

**Comment by Varinder-Dhillon0** [comment]
this one looks good @shera-bhai make a pr
