### ISSUE TITLE
Updating Admin Page Ui

### ISSUE THREAD

**Issue by Varinder-Dhillon0** [Open-Source-Chandigarh/Brewtopia#98]
**_what you need to do_** 
- Update ui colors.
- Improve ui.

Use this design for making ui https://davur.dexignzone.com/react/demo/dashboard

**Comment by IrfanshaikH-7** [comment]
I'll like to work on this - .....

**Comment by Varinder-Dhillon0** [comment]
yes @IrfanshaikH-7 I don't have plan to shift to tailwind css because we will have to change all the css into tailwind css.

**Comment by IrfanshaikH-7** [comment]
Question- do we have to replicate the above-mentioned UI as it is. @Varinder-Dhillon0

**Comment by Varinder-Dhillon0** [comment]
yes @IrfanshaikH-7

**Comment by IrfanshaikH-7** [comment]
About the other issue! can I work on that -
And I would like to know - is the proxy thing causing conflict with main codebase.

**Comment by Varinder-Dhillon0** [comment]
Hey @IrfanshaikH-7 no proxy is not causing conflict. for the other issue you should create new issue and i will assign you there

**Comment by IrfanshaikH-7** [comment]
Okay I'll be creating issues on Charts issue

**Comment by Varinder-Dhillon0** [comment]
you already have access to backend code @IrfanshaikH-7

**Comment by IrfanshaikH-7** [comment]
I looked into it... And something's need to be added into backend to fully work on dashboard statistics -   please lemmi do it. ... before that could you please let me work on the issue regarding filtering ..
